// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pet-system/CoinShop.tsx": () => import("../components/mockups/pet-system/CoinShop.tsx"),
  "./components/mockups/pet-system/PetScreen.tsx": () => import("../components/mockups/pet-system/PetScreen.tsx"),
  "./components/mockups/statistics/Compact.tsx": () => import("../components/mockups/statistics/Compact.tsx"),
  "./components/mockups/statistics/Insights.tsx": () => import("../components/mockups/statistics/Insights.tsx")
};
